name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight (UTC)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: shubhamniranjan78 # Replace with your GitHub username

      - name: Push Snake Animation to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output # Replace with the branch where your animation is stored
          build_dir: dist # Replace with the directory of the generated file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
